onerror {resume}
quietly WaveActivateNextPane {} 0
delete wave *
add wave -noupdate /fourbitpredictorprogramtest/uut/CLOCK
#add wave -noupdate /fourbitpredictorprogramtest/uut/INIT
add wave -noupdate /fourbitpredictorprogramtest/uut/ADDR
add wave -noupdate /fourbitpredictorprogramtest/uut/OUTCOME
add wave -noupdate /fourbitpredictorprogramtest/uut/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/MISSES
#add wave -noupdate /fourbitpredictorprogramtest/uut/miss_in
#add wave -noupdate /fourbitpredictorprogramtest/uut/prediction_out
#add wave -noupdate /fourbitpredictorprogramtest/uut/demen0
#add wave -noupdate /fourbitpredictorprogramtest/uut/demen1
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o0
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o1
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o2
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o3
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o4
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o5
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o6
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o7
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o8
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o9
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o10
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o11
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o12
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o13
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o14
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20o15
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en0
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en1
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en2
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en3
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en4
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en5
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en6
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en7
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en8
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en9
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en10
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en11
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en12
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en13
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en14
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem20en15
#add wave -noupdate /fourbitpredictorprogramtest/uut/A0
#add wave -noupdate /fourbitpredictorprogramtest/uut/B0
#add wave -noupdate /fourbitpredictorprogramtest/uut/C0
#add wave -noupdate /fourbitpredictorprogramtest/uut/D0
#add wave -noupdate /fourbitpredictorprogramtest/uut/E0
#add wave -noupdate /fourbitpredictorprogramtest/uut/F0
#add wave -noupdate /fourbitpredictorprogramtest/uut/G0
#add wave -noupdate /fourbitpredictorprogramtest/uut/H0
#add wave -noupdate /fourbitpredictorprogramtest/uut/I0
#add wave -noupdate /fourbitpredictorprogramtest/uut/J0
#add wave -noupdate /fourbitpredictorprogramtest/uut/K0
#add wave -noupdate /fourbitpredictorprogramtest/uut/L0
#add wave -noupdate /fourbitpredictorprogramtest/uut/M0
#add wave -noupdate /fourbitpredictorprogramtest/uut/N0
#add wave -noupdate /fourbitpredictorprogramtest/uut/O0
#add wave -noupdate /fourbitpredictorprogramtest/uut/P0
#add wave -noupdate /fourbitpredictorprogramtest/uut/OUTPUT0
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o0
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o1
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o2
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o3
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o4
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o5
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o6
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o7
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o8
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o9
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o10
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o11
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o12
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o13
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o14
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21o15
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en0
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en1
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en2
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en3
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en4
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en5
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en6
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en7
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en8
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en9
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en10
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en11
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en12
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en13
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en14
#add wave -noupdate /fourbitpredictorprogramtest/uut/dem21en15
#add wave -noupdate /fourbitpredictorprogramtest/uut/A1
#add wave -noupdate /fourbitpredictorprogramtest/uut/B1
#add wave -noupdate /fourbitpredictorprogramtest/uut/C1
#add wave -noupdate /fourbitpredictorprogramtest/uut/D1
#add wave -noupdate /fourbitpredictorprogramtest/uut/E1
#add wave -noupdate /fourbitpredictorprogramtest/uut/F1
#add wave -noupdate /fourbitpredictorprogramtest/uut/G1
#add wave -noupdate /fourbitpredictorprogramtest/uut/H1
#add wave -noupdate /fourbitpredictorprogramtest/uut/I1
#add wave -noupdate /fourbitpredictorprogramtest/uut/J1
#add wave -noupdate /fourbitpredictorprogramtest/uut/K1
#add wave -noupdate /fourbitpredictorprogramtest/uut/L1
#add wave -noupdate /fourbitpredictorprogramtest/uut/M1
#add wave -noupdate /fourbitpredictorprogramtest/uut/N1
#add wave -noupdate /fourbitpredictorprogramtest/uut/O1
#add wave -noupdate /fourbitpredictorprogramtest/uut/P1
#add wave -noupdate /fourbitpredictorprogramtest/uut/OUTPUT1
add wave -noupdate /fourbitpredictorprogramtest/uut/demux/enable0
add wave -noupdate /fourbitpredictorprogramtest/uut/demux/enable1
#add wave -noupdate /fourbitpredictorprogramtest/uut/demux20/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/demux20/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count00/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count00/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count00/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count00/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count00/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count01/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count01/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count01/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count01/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count01/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count02/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count02/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count02/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count02/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count02/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count03/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count03/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count03/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count03/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count03/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count04/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count04/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count04/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count04/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count04/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count05/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count05/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count05/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count05/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count05/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count06/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count06/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count06/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count06/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count06/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count07/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count07/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count07/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count07/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count07/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count08/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count08/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count08/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count08/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count08/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count09/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count09/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count09/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count09/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count09/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count010/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count010/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count010/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count010/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count010/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count011/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count011/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count011/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count011/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count011/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count012/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count012/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count012/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count012/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count012/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count013/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count013/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count013/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count013/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count013/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count014/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count014/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count014/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count014/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count014/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count015/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count015/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count015/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count015/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count015/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/mux20/OUTPUT
#add wave -noupdate /fourbitpredictorprogramtest/uut/demux21/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count10/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count10/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count10/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count10/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count10/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count11/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count11/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count11/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count11/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count11/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count12/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count12/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count12/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count12/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count12/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count13/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count13/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count13/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count13/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count13/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count14/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count14/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count14/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count14/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count14/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count15/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count15/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count15/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count15/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count15/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count16/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count16/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count16/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count16/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count16/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count17/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count17/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count17/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count17/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count17/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count18/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count18/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count18/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count18/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count18/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count19/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count19/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count19/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count19/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count19/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count110/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count110/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count110/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count110/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count110/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count111/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count111/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count111/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count111/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count111/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count112/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count112/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count112/PREDICTION
#add wave -noupdate /fourbitpredictorprogramtest/uut/count112/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count112/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count113/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count113/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count113/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count113/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count113/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count114/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count114/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count114/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count114/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count114/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/count115/OUTCOME
#add wave -noupdate /fourbitpredictorprogramtest/uut/count115/ENABLE
#add wave -noupdate /fourbitpredictorprogramtest/uut/count115/PREDICTION
add wave -noupdate /fourbitpredictorprogramtest/uut/count115/count
#add wave -noupdate /fourbitpredictorprogramtest/uut/count115/predic
#add wave -noupdate /fourbitpredictorprogramtest/uut/mux21/OUTPUT
#add wave -noupdate /fourbitpredictorprogramtest/uut/mux/A
#add wave -noupdate /fourbitpredictorprogramtest/uut/mux/B
#add wave -noupdate /fourbitpredictorprogramtest/uut/mux/OUTPUT
#add wave -noupdate /fourbitpredictorprogramtest/uut/count/temp
add wave -noupdate /fourbitpredictorprogramtest/uut/global/column
#add wave -noupdate /fourbitpredictorprogramtest/uut/global/temp

TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {50050 ns} {51050 ns}